# Logging (console via QEMU UART)
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_CPP=y
CONFIG_STD_CPP17=y

# Sensible default for early bring-up
CONFIG_MAIN_STACK_SIZE=2048
